# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d16141e5e11c651d944c5c2dfab6603b9e13a3e376c7e813f56ad02e3565ef037327d8be682c5826e47b87dac25100e8a6c3893e994b52650a068997ab3707ed

test:
  secret_key_base: 3ac52fe42611b430437410958f287378d57e3679462de4551bc68e2c4c567ffdb60360460e539c18c3fb3ae0775e3fc3cd31f0e2149585a6cca1d86422b4d70d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
